# Generated by Django 4.2.2 on 2023-07-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0011_hero_description'),
        ('modelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ormapp.student'),
        ),
    ]
