# Generated by Django 4.2.2 on 2023-07-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0011_hero_description'),
        ('modelling', '0004_book_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ormapp.student')),
            ],
        ),
    ]
