# Generated by Django 4.2.2 on 2023-08-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0011_hero_description'),
        ('modelling', '0005_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='ormapp.student'),
        ),
    ]
