# Generated by Django 4.2.2 on 2023-07-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0004_rename_category2_categoryhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormapp.categoryhero'),
        ),
    ]
