# Generated by Django 4.2.2 on 2023-07-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
