# Generated by Django 4.2.2 on 2023-07-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0007_rename_user_user2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User2',
            new_name='UserS',
        ),
    ]
