# Generated by Django 4.2.2 on 2023-07-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0008_rename_user2_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserS',
            new_name='People',
        ),
    ]
