# Generated by Django 4.2.2 on 2023-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0009_rename_users_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
