# Generated by Django 4.2.2 on 2023-07-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0010_alter_people_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(default='thiusi'),
        ),
    ]
