# Generated by Django 4.2.2 on 2023-08-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormpractoce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
